version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      - APP_PORT=8010
      - WEB_ROOT=/app/www
      - DATA_DIR=/app/data
      - API_TOKEN=changeme-local-token
    volumes:
      - ./app/www:/app/www:ro
      - ./data:/app/data
    expose:
      - "8010"

  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
