version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov-data-poc-app
    environment:
      - APP_PORT=8010
      - WEB_ROOT=/app/www
      - DATA_DIR=/app/data
      # 必要ならトークンを有効化
      # - API_TOKEN=changeme-local-token
    volumes:
      - ./app/www:/app/www:ro
      - ./data:/app/data
    expose:
      - "8010"

  proxy:
    image: caddy:2
    container_name: gov-data-poc-proxy
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
