services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    expose:
      - "8010"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8010/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx:1.27
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1/health"]
      interval: 20s
      timeout: 5s
      retries: 5
