version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov-data-poc-app-1
    command: uvicorn app.qa_service:app --host 0.0.0.0 --port 8010 --proxy-headers
    environment:
      - TZ=Asia/Tokyo
      - APP_ENV=prod
    volumes:
      - ./data:/app/data
      - ./www:/app/www:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8010/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  proxy:
    image: nginx:1.27
    container_name: gov-data-poc-proxy-1
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
    restart: unless-stopped
