version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      - API_TOKEN=changeme-local-token
      - APP_PORT=8010
      - VERSION=dev
      - BUILD_TIME=unknown
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data:rw
    expose:
      - "8010"

  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro

networks:
  default:
    name: gov-data-poc_default
