version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov-data-poc-app
    ports:
      - "8010:8010"
    environment:
      APP_PORT: "8010"
      WEB_ROOT: /app/www
      DATA_DIR: /app/data
      API_TOKEN: "changeme-local-token"
      VERSION: "dev"
    volumes:
      - ./app/www:/app/www:ro            # index.html をローカルから反映したい場合
      - ./data:/app/data                  # 収集データ永続化（feedback / flags）
    restart: unless-stopped
