version: "3.9"

services:
  app:
    build: .
    container_name: gov-data-poc-app
    environment:
      - APP_PORT=8010
      - WEB_ROOT=/app/www
      - DATA_DIR=/app/data
      - API_TOKEN=changeme-local-token
      - VERSION=dev
    volumes:
      - ./app/www:/app/www:ro
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://127.0.0.1:8010/health')"]
      interval: 10s
      timeout: 3s
      retries: 10

  proxy:
    image: nginx:1.27
    container_name: gov-data-poc-proxy
    depends_on:
      app:
        condition: service_started
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# 例: nginx/default.conf
# server {
#   listen 80;
#   location / { proxy_pass http://app:8010; proxy_set_header Host $host; }
# }
