version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      # .env があれば優先。なければ changeme-local-token
      - API_TOKEN=${API_TOKEN:-changeme-local-token}
      - VERSION=dev
    volumes:
      # ホストに結果を残す（./data/feedback, ./data/flags）
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 10

  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      # ここが重要：作成済みの nginx.conf をコンテナの /etc/nginx/nginx.conf に ReadOnly でマウント
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 10

# デフォルトネットワークで OK（service 名で名前解決される）
