version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VERSION: "dev"
      API_TOKEN: "changeme-local-token"
      APP_PORT: "8010"
      WEB_ROOT: "/app/www"
      DATA_DIR: "/app/data"
    expose:
      - "8010"
    volumes:
      - ./app/www:/app/www:ro           # index.html をホットリロード
      - ./data:/app/data                # feedback/flags を永続化
    restart: unless-stopped

  proxy:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
