version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      - API_TOKEN=${API_TOKEN:-changeme-local-token}
      - VERSION=dev
    volumes:
      - ./data:/app/data
    expose:
      - "8010"

  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
