version: "3.9"

services:
  app:
    build:
      context: .
    image: gov-data-poc-app:local
    command: ["python", "-m", "uvicorn", "qa_service:app", "--host", "0.0.0.0", "--port", "8010"]
    expose:
      - "8010"
    environment:
      - TZ=Asia/Tokyo
      # ← ここで API トークンを渡す（ご指定の値）
      - API_TOKEN=changeme-local-token
    volumes:
      # /app/data がホストの ./data に見える
      - ./data:/app/data

  proxy:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      # nginx 設定を /etc/nginx/nginx.conf へ
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
