version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gov-data-poc-app-1
    environment:
      - VERSION=${VERSION:-dev}
      - BUILD_TIME=${BUILD_TIME:-unknown}
      - API_TOKEN=${API_TOKEN:-changeme-local-token}
    volumes:
      - ./data:/app/data            # フィードバック/フラグをホストに永続化
      - ./www:/app/www              # もし将来FastAPIで静的配信するなら
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request,sys\nu='http://127.0.0.1:8010/health'\nresp=urllib.request.urlopen(u,timeout=2)\nprint(resp.status)\nPY"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - gov-data-poc_default

  proxy:
    image: nginx:1.27
    container_name: gov-data-poc-proxy-1
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - gov-data-poc_default

networks:
  gov-data-poc_default:
    driver: bridge
