version: "3.9"

services:
  app:
    build:
      context: .
    image: gov-data-poc-app:local
    command: ["python", "-m", "uvicorn", "qa_service:app", "--host", "0.0.0.0", "--port", "8010"]
    environment:
      - TZ=Asia/Tokyo
      # 任意: API_TOKEN を使うならここで設定
      # - API_TOKEN=changeme
      - DATA_DIR=/app/data
    volumes:
      # ← ホスト側 ./data がコンテナ /app/data と同期されます
      - ./data:/app/data
    expose:
      - "8010"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3

  proxy:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
