version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      - APP_PORT=8010
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./www:/usr/share/nginx/html:ro
      - ./data:/app/data                    # flags/ や feedback/ を見る用（ls するなら必要）
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
