version: "3.9"

services:
  app:
    build:
      context: .
    image: gov-data-poc-app:local
    command: ["python", "-m", "uvicorn", "qa_service:app", "--host", "0.0.0.0", "--port", "8010"]
    expose:
      - "8010"
    environment:
      - TZ=Asia/Tokyo
      - API_TOKEN=changeme-local-token   # ← ここで固定 or .env でもOK
      - VERSION=dev
    volumes:
      - ./data:/app/data                  # ← /app/data がホスト ./data に見える
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health | jq -e .ok >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  proxy:
    image: nginx:1.27
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
