version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      APP_PORT: "8010"
      WEB_ROOT: /app/www
      DATA_DIR: /app/data
      VERSION: "dev"
      API_TOKEN: "changeme-local-token"   # ←必要に応じ変更
    volumes:
      - ./app/www:/app/www:ro
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8010/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
