version: "3.9"
services:
  app:
    image: gov-data-poc-app:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VERSION=dev
      - BUILD_TIME=${BUILD_TIME:-unknown}
      - APP_PORT=8010
      - WEB_ROOT=/app/www
      - DATA_DIR=/app/data
      - API_TOKEN=changeme-local-token
    ports:
      - "8010:8010"
    # ログやフラグをホストに残したい場合は ↓ を有効化（任意）
    # volumes:
    #   - ./data:/app/data
  proxy:
    image: nginx:1.27
    depends_on:
      - app
    ports:
      - "8080:80"
    command: >
      /bin/sh -c 'printf "server { listen 80; location / { proxy_pass http://app:8010; proxy_http_version 1.1; proxy_set_header Host $$host; } }" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
