version: "3.9"
services:
  app:
    build: .
    container_name: gov-data-poc-app-1
    environment:
      - API_TOKEN=changeme-local-token
      - VERSION=dev
      - BUILD_TIME=unknown
    volumes:
      - ./data:/app/data
    expose:
      - "8010"

  proxy:
    image: nginx:1.25-alpine
    container_name: gov-data-poc-proxy-1
    depends_on:
      - app
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
