version: "3.9"

name: gov-data-poc

networks:
  gov-data-poc-net:

volumes:
  app_logs:
  app_data:

services:
  app:
    # GHCR のあなたのパッケージ名とタグに置き換え済み
    image: ghcr.io/tircbq7ey-afk/gov-data-poc-app:v0.1.1
    restart: always
    env_file: .env
    expose:
      - "8010"
    volumes:
      - app_logs:/var/log/app
      - app_data:/data
      # ローカルの data/ を与える場合は下の2行を使う
      # - ./data:/data
      # - ./logs:/var/log/app
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - gov-data-poc-net

  proxy:
    image: nginx:stable
    restart: always
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # /static を配信したい場合は以下を使う
      # - ./static:/usr/share/nginx/html:ro
    networks:
      - gov-data-poc-net
