version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov-data-poc-app
    environment:
      APP_PORT: "8010"
      WEB_ROOT: "/app/www"
      DATA_DIR: "/app/data"
      # 管理 API を守るなら設定（/admin/reindex で要求）
      # API_TOKEN: "changeme-local-token"
    volumes:
      - ./data:/app/data
      - ./app/www:/app/www
    expose:
      - "8010"

  proxy:
    image: caddy:2
    container_name: gov-data-poc-proxy
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
