# docker-compose.proxy.yml
services:
  proxy:
    container_name: gov-data-poc-proxy
    image: nginx:1.25-alpine
    depends_on:
      app:
        condition: service_started         # app 起動後に proxy を起動
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html:ro  # static/index.html を配信
    healthcheck:
      # Nginx 自身で返す /health を 200 で確認
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/health | grep -q ok"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - gov_data_poc_net

# ここで networks は prod.yml のものと同名にして共有されます
