version: "3.9"

services:
  app:
    build:
      context: .
    image: gov-data-poc-app:local
    command: ["python", "-m", "uvicorn", "qa_service:app", "--host", "0.0.0.0", "--port", "8010", "--proxy-headers"]
    expose:
      - "8010"
    environment:
      - TZ=Asia/Tokyo
      - API_TOKEN=changeme-local-token
      # （必要に応じて）VERSION/BUILD_TIME もここで渡せます
      # - VERSION=dev
      # - BUILD_TIME=2025-10-19T00:00:00Z
    volumes:
      # /app/data がホスト側 ./data に見える（feedback/flags が自動で出てくる）
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  proxy:
    image: nginx:1.27
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
