version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # 任意のトークンに変更可。PowerShell からは x-api-key ヘッダで渡す
      - API_TOKEN=changeme-local-token
      - PYTHONUNBUFFERED=1
      - APP_PORT=8010
    volumes:
      # アプリ本体（読み取り専用で OK）
      - ./app:/app/app:ro
      # 生成物（フィードバックやフラグ）をホストに永続化
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8010/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  proxy:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      # ブラウザは http://127.0.0.1:8080/
      - "8080:80"
    volumes:
      # 静的ファイル
      - ./www:/usr/share/nginx/html:ro
      # あなたのリポの nginx フォルダをそのまま利用
      # （下の nginx.conf / default.conf をこのあと差し替え）
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
