version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    ports:
      - "8010:8010"
    environment:
      - API_TOKEN=changeme-local-token
      - APP_PORT=8010
      - WEB_ROOT=/app/www
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
      - ./app/www:/app/www
    restart: unless-stopped
