version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: "8010"
      WEB_ROOT: /app/www
      DATA_DIR: /app/data
      API_TOKEN: "${API_TOKEN:-changeme-local-token}"
    volumes:
      - ./data:/app/data
      - ./www:/app/www:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8010/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  proxy:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
    restart: unless-stopped
