version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gov-data-poc-app:local
    environment:
      - TZ=Asia/Tokyo
      # API トークンを使う場合は↓をセット（省略すれば認証なし）
      # - API_TOKEN=changeme
      - VERSION=prod
    expose:
      - "8010"
    volumes:
      # ★ これで /app/data がホスト ./data に見える
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  proxy:
    image: nginx:1.27
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
