version: "3.9"

services:
  app:
    build:
      context: .
    image: gov-data-poc-app:local
    command: ["python", "-m", "uvicorn", "app.qa_service:app", "--host", "0.0.0.0", "--port", "8010"]
    expose:
      - "8010"
    environment:
      - TZ=Asia/Tokyo
      - API_TOKEN=changeme-local-token
      - VERSION=dev
      - BUILD_TIME=${BUILD_TIME-unknown}
      - DATA_DIR=/app/data
    volumes:
      # /app/data がホストの ./data とつながる（feedback/ や flags/ が見える）
      - ./data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 5

  proxy:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
